server:
  datasource:
    url: jdbc:mysql://localhost:3306/sky_take_out?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
sky:
  wechat:
    appid: wx424442f77d8c24b1
    secret: 88be0cd53a223a17a4a2f4de81e4dc6d