server:
  datasource:
    url: jdbc:mysql://localhost:3306/sky_take_out?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

sky:
  jwt:
    admin-secret-key: your_admin_secret_key
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: your_user_secret_key
    user-ttl: 1800000
    user-token-name: token
  wechat:
    app-id: your_app_id
    app-secret: your_app_secret