server:
  port: 8090

spring:
  profiles:
    active: dev              # 激活 dev 环境
  application:
    name: skt-server
  datasource:
    url: ${server.datasource.url}
    username: ${server.datasource.username}
    password: ${server.datasource.password}
  data:
    redis:
      host: ${server.redis.host}
      port: ${server.redis.port}
      database: ${server.redis.database}
      # 连接池配置
      lettuce:
        pool:
          max-active: 8        # 最大连接数
          max-idle: 8          # 最大空闲连接
          min-idle: 0          # 最小空闲连接
          max-wait: 100ms      # 最大等待时间

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  packages-to-scan: com.liuheng.controller
#  swagger-ui:
#    path: /swagger-ui.html
#    defaultModelsExpandDepth: 1
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类
    # 是否显示标签分组
    enableGroup: true

page helper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

sky:
  jwt:
    admin-secret-key: herrylo-secret-key-32-bytes-long-12345678
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: herrylo-secret-key-32-bytes-long-12345678
    user-ttl: 7200000
    user-token-name: token
